"""empty message

Revision ID: 0c4e036d2bfb
Revises: 576028e00c8f
Create Date: 2023-10-10 20:33:40.937327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4e036d2bfb'
down_revision: Union[str, None] = '576028e00c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('nom', sa.String(), nullable=False))
    op.add_column('utilisateur', sa.Column('prenoms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'prenoms')
    op.drop_column('utilisateur', 'nom')
    # ### end Alembic commands ###
