"""rapport

Revision ID: 19a6ff2d1aa5
Revises: ea59668162d9
Create Date: 2023-11-06 18:12:04.561507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a6ff2d1aa5'
down_revision: Union[str, None] = 'ea59668162d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapport',
    sa.Column('id_rapport', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fichier', sa.String(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rapport')
    # ### end Alembic commands ###
