"""modification 8

Revision ID: 1dc189fde562
Revises: b21e884261bf
Create Date: 2023-10-10 10:19:41.280312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc189fde562'
down_revision: Union[str, None] = 'b21e884261bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actionaire_id_act_marchandise_fkey', 'actionaire', type_='foreignkey')
    op.drop_column('actionaire', 'id_act_marchandise')
    op.add_column('marchandises', sa.Column('id_act_marchandise', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marchandises', 'actionaire', ['id_act_marchandise'], ['id_actionaire'], onupdate='cascade', ondelete='cascade')
    op.drop_column('marchandises', 'id_operation_marchandise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marchandises', sa.Column('id_operation_marchandise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.drop_column('marchandises', 'id_act_marchandise')
    op.add_column('actionaire', sa.Column('id_act_marchandise', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('actionaire_id_act_marchandise_fkey', 'actionaire', 'marchandises', ['id_act_marchandise'], ['id_marchandise'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
