"""ajout_attr_personne_resp_act

Revision ID: 231a11599b3d
Revises: 1dc189fde562
Create Date: 2023-10-10 10:48:34.437386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231a11599b3d'
down_revision: Union[str, None] = '1dc189fde562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionaire', sa.Column('personne', sa.Boolean(), nullable=False))
    op.add_column('responsable_navire', sa.Column('personne', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsable_navire', 'personne')
    op.drop_column('actionaire', 'personne')
    # ### end Alembic commands ###
