"""modification 3

Revision ID: 30d06df0f53b
Revises: 85a90136c8d3
Create Date: 2023-10-09 12:12:55.876201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d06df0f53b'
down_revision: Union[str, None] = '85a90136c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionaire', sa.Column('id_act_marchandise', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actionaire', 'marchandises', ['id_act_marchandise'], ['id_marchandise'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('marchandises_id_actionaire_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.drop_column('marchandises', 'id_actionaire_marchandise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marchandises', sa.Column('id_actionaire_marchandise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('marchandises_id_actionaire_marchandise_fkey', 'marchandises', 'actionaire', ['id_actionaire_marchandise'], ['id_actionaire'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'actionaire', type_='foreignkey')
    op.drop_column('actionaire', 'id_act_marchandise')
    # ### end Alembic commands ###
