"""resp_to_accost_2

Revision ID: 3b19e0be5360
Revises: 1b825489df05
Create Date: 2023-10-30 14:23:42.066618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b19e0be5360'
down_revision: Union[str, None] = '1b825489df05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accostage', sa.Column('id_resp', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accostage', 'responsable_navire', ['id_resp'], ['id_resp'], onupdate='cascade', ondelete='cascade')
    op.add_column('responsable_navire', sa.Column('id_accoste_resp', sa.Integer(), nullable=False))
    op.drop_constraint('responsable_navire_id_navire_resp_fkey', 'responsable_navire', type_='foreignkey')
    op.create_foreign_key(None, 'responsable_navire', 'accostage', ['id_accoste_resp'], ['id_accostage'], onupdate='cascade', ondelete='cascade')
    op.drop_column('responsable_navire', 'id_navire_resp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsable_navire', sa.Column('id_navire_resp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'responsable_navire', type_='foreignkey')
    op.create_foreign_key('responsable_navire_id_navire_resp_fkey', 'responsable_navire', 'navires', ['id_navire_resp'], ['id_navire'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('responsable_navire', 'id_accoste_resp')
    op.drop_constraint(None, 'accostage', type_='foreignkey')
    op.drop_column('accostage', 'id_resp')
    # ### end Alembic commands ###
