"""empty message

Revision ID: 3cfd930df251
Revises: 0c4e036d2bfb
Create Date: 2023-10-11 09:32:02.927389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfd930df251'
down_revision: Union[str, None] = '0c4e036d2bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('code_activation', sa.String(), nullable=False))
    op.add_column('utilisateur', sa.Column('status_compte', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'status_compte')
    op.drop_column('utilisateur', 'code_activation')
    # ### end Alembic commands ###
