"""empty message

Revision ID: 576028e00c8f
Revises: 83c2fd4dc942
Create Date: 2023-10-10 14:47:04.637345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576028e00c8f'
down_revision: Union[str, None] = '83c2fd4dc942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marchandises', sa.Column('id_port_march', sa.Integer(), nullable=True))
    op.drop_constraint('marchandises_id_port_prov_fkey', 'marchandises', type_='foreignkey')
    op.drop_constraint('marchandises_id_port_dest_fkey', 'marchandises', type_='foreignkey')
    op.create_foreign_key(None, 'marchandises', 'ports', ['id_port_march'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.drop_column('marchandises', 'id_port_prov')
    op.drop_column('marchandises', 'id_port_dest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marchandises', sa.Column('id_port_dest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('marchandises', sa.Column('id_port_prov', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.create_foreign_key('marchandises_id_port_dest_fkey', 'marchandises', 'ports', ['id_port_dest'], ['id_port'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('marchandises_id_port_prov_fkey', 'marchandises', 'ports', ['id_port_prov'], ['id_port'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('marchandises', 'id_port_march')
    # ### end Alembic commands ###
