"""add created and updated

Revision ID: 63a36a80a0f1
Revises: 6ec1ad7ed6f7
Create Date: 2023-10-08 08:56:25.212239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a36a80a0f1'
down_revision: Union[str, None] = '6ec1ad7ed6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
