"""add created and updated

Revision ID: 6ec1ad7ed6f7
Revises: 2fb9b0f498f2
Create Date: 2023-10-08 08:42:33.890983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec1ad7ed6f7'
down_revision: Union[str, None] = '2fb9b0f498f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
