"""modification 2

Revision ID: 85a90136c8d3
Revises: d0da6e928e25
Create Date: 2023-10-09 12:01:43.769306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a90136c8d3'
down_revision: Union[str, None] = 'd0da6e928e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accostage', sa.Column('id_navire_accoste', sa.Integer(), nullable=True))
    op.add_column('accostage', sa.Column('id_port_accoste', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accostage', 'ports', ['id_port_accoste'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'accostage', 'navires', ['id_navire_accoste'], ['id_navire'], onupdate='cascade', ondelete='cascade')
    op.add_column('marchandises', sa.Column('id_accostage_marchandise', sa.Integer(), nullable=False))
    op.drop_constraint('marchandises_id_navire_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.create_foreign_key(None, 'marchandises', 'accostage', ['id_accostage_marchandise'], ['id_accostage'], onupdate='cascade', ondelete='cascade')
    op.drop_column('marchandises', 'id_navire_marchandise')
    op.create_unique_constraint(None, 'navires', ['immatricule_navire'])
    op.drop_constraint('navires_id_accostage_navire_fkey', 'navires', type_='foreignkey')
    op.drop_constraint('navires_id_port_accoste_fkey', 'navires', type_='foreignkey')
    op.drop_column('navires', 'id_port_accoste')
    op.drop_column('navires', 'id_accostage_navire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('navires', sa.Column('id_accostage_navire', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('navires', sa.Column('id_port_accoste', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('navires_id_port_accoste_fkey', 'navires', 'ports', ['id_port_accoste'], ['id_port'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('navires_id_accostage_navire_fkey', 'navires', 'accostage', ['id_accostage_navire'], ['id_accostage'])
    op.drop_constraint(None, 'navires', type_='unique')
    op.add_column('marchandises', sa.Column('id_navire_marchandise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.create_foreign_key('marchandises_id_navire_marchandise_fkey', 'marchandises', 'navires', ['id_navire_marchandise'], ['id_navire'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('marchandises', 'id_accostage_marchandise')
    op.drop_constraint(None, 'accostage', type_='foreignkey')
    op.drop_constraint(None, 'accostage', type_='foreignkey')
    op.drop_column('accostage', 'id_port_accoste')
    op.drop_column('accostage', 'id_navire_accoste')
    # ### end Alembic commands ###
