"""modification 7

Revision ID: b21e884261bf
Revises: 7ee2df178042
Create Date: 2023-10-10 07:57:05.329702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b21e884261bf'
down_revision: Union[str, None] = '7ee2df178042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('marchandises_id_operation_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.drop_column('marchandises', 'id_operation_marchandise')
    op.drop_table('operation')
    op.add_column('marchandises', sa.Column('nom_operation', sa.String(), nullable=False))
    op.add_column('marchandises', sa.Column('type_operation', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marchandises', sa.Column('id_operation_marchandise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('marchandises_id_operation_marchandise_fkey', 'marchandises', 'operation', ['id_operation_marchandise'], ['id_operation'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('marchandises', 'type_operation')
    op.drop_column('marchandises', 'nom_operation')
    op.create_table('operation',
    sa.Column('id_operation', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_operation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type_operation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_operation', name='operation_pkey')
    )
    # ### end Alembic commands ###
