"""cascade

Revision ID: d0da6e928e25
Revises: 63a36a80a0f1
Create Date: 2023-10-08 09:24:18.139888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0da6e928e25'
down_revision: Union[str, None] = '63a36a80a0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('marchandises_id_operation_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.drop_constraint('marchandises_id_navire_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.drop_constraint('marchandises_id_actionaire_marchandise_fkey', 'marchandises', type_='foreignkey')
    op.drop_constraint('marchandises_id_port_dest_fkey', 'marchandises', type_='foreignkey')
    op.drop_constraint('marchandises_id_port_prov_fkey', 'marchandises', type_='foreignkey')
    op.create_foreign_key(None, 'marchandises', 'ports', ['id_port_prov'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'marchandises', 'operation', ['id_operation_marchandise'], ['id_operation'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'marchandises', 'ports', ['id_port_dest'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'marchandises', 'actionaire', ['id_actionaire_marchandise'], ['id_actionaire'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'marchandises', 'navires', ['id_navire_marchandise'], ['id_navire'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('navires_id_port_accoste_fkey', 'navires', type_='foreignkey')
    op.drop_constraint('navires_id_pays_navire_fkey', 'navires', type_='foreignkey')
    op.drop_constraint('navires_id_port_dest_fkey', 'navires', type_='foreignkey')
    op.drop_constraint('navires_id_port_prov_fkey', 'navires', type_='foreignkey')
    op.create_foreign_key(None, 'navires', 'ports', ['id_port_dest'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'navires', 'ports', ['id_port_accoste'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'navires', 'ports', ['id_port_prov'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'navires', 'pays', ['id_pays_navire'], ['id_pays'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('pays_id_continent_pays_fkey', 'pays', type_='foreignkey')
    op.create_foreign_key(None, 'pays', 'continents', ['id_continent_pays'], ['id_continent'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('ports_id_pays_port_fkey', 'ports', type_='foreignkey')
    op.create_foreign_key(None, 'ports', 'pays', ['id_pays_port'], ['id_pays'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('responsable_navire_id_navire_resp_fkey', 'responsable_navire', type_='foreignkey')
    op.create_foreign_key(None, 'responsable_navire', 'navires', ['id_navire_resp'], ['id_navire'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responsable_navire', type_='foreignkey')
    op.create_foreign_key('responsable_navire_id_navire_resp_fkey', 'responsable_navire', 'navires', ['id_navire_resp'], ['id_navire'])
    op.drop_constraint(None, 'ports', type_='foreignkey')
    op.create_foreign_key('ports_id_pays_port_fkey', 'ports', 'pays', ['id_pays_port'], ['id_pays'])
    op.drop_constraint(None, 'pays', type_='foreignkey')
    op.create_foreign_key('pays_id_continent_pays_fkey', 'pays', 'continents', ['id_continent_pays'], ['id_continent'])
    op.drop_constraint(None, 'navires', type_='foreignkey')
    op.drop_constraint(None, 'navires', type_='foreignkey')
    op.drop_constraint(None, 'navires', type_='foreignkey')
    op.drop_constraint(None, 'navires', type_='foreignkey')
    op.create_foreign_key('navires_id_port_prov_fkey', 'navires', 'ports', ['id_port_prov'], ['id_port'])
    op.create_foreign_key('navires_id_port_dest_fkey', 'navires', 'ports', ['id_port_dest'], ['id_port'])
    op.create_foreign_key('navires_id_pays_navire_fkey', 'navires', 'pays', ['id_pays_navire'], ['id_pays'])
    op.create_foreign_key('navires_id_port_accoste_fkey', 'navires', 'ports', ['id_port_accoste'], ['id_port'])
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.drop_constraint(None, 'marchandises', type_='foreignkey')
    op.create_foreign_key('marchandises_id_port_prov_fkey', 'marchandises', 'ports', ['id_port_prov'], ['id_port'])
    op.create_foreign_key('marchandises_id_port_dest_fkey', 'marchandises', 'ports', ['id_port_dest'], ['id_port'])
    op.create_foreign_key('marchandises_id_actionaire_marchandise_fkey', 'marchandises', 'actionaire', ['id_actionaire_marchandise'], ['id_actionaire'])
    op.create_foreign_key('marchandises_id_navire_marchandise_fkey', 'marchandises', 'navires', ['id_navire_marchandise'], ['id_navire'])
    op.create_foreign_key('marchandises_id_operation_marchandise_fkey', 'marchandises', 'operation', ['id_operation_marchandise'], ['id_operation'])
    # ### end Alembic commands ###
