"""'dernier_modification'

Revision ID: d908d9f086bf
Revises: 3cfd930df251
Create Date: 2023-10-26 07:24:26.510051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd908d9f086bf'
down_revision: Union[str, None] = '3cfd930df251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accostage', sa.Column('id_port_prov', sa.Integer(), nullable=False))
    op.add_column('accostage', sa.Column('id_port_dest', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accostage', 'ports', ['id_port_dest'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'accostage', 'ports', ['id_port_prov'], ['id_port'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('navires_id_port_dest_fkey', 'navires', type_='foreignkey')
    op.drop_constraint('navires_id_port_prov_fkey', 'navires', type_='foreignkey')
    op.drop_column('navires', 'id_port_dest')
    op.drop_column('navires', 'id_port_prov')
    op.add_column('ports', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'status')
    op.add_column('navires', sa.Column('id_port_prov', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('navires', sa.Column('id_port_dest', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('navires_id_port_prov_fkey', 'navires', 'ports', ['id_port_prov'], ['id_port'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('navires_id_port_dest_fkey', 'navires', 'ports', ['id_port_dest'], ['id_port'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'accostage', type_='foreignkey')
    op.drop_constraint(None, 'accostage', type_='foreignkey')
    op.drop_column('accostage', 'id_port_dest')
    op.drop_column('accostage', 'id_port_prov')
    # ### end Alembic commands ###
