"""resp_to_accost_3

Revision ID: ea59668162d9
Revises: 3b19e0be5360
Create Date: 2023-10-30 14:29:35.869740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea59668162d9'
down_revision: Union[str, None] = '3b19e0be5360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accostage_id_resp_fkey', 'accostage', type_='foreignkey')
    op.drop_column('accostage', 'id_resp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accostage', sa.Column('id_resp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('accostage_id_resp_fkey', 'accostage', 'responsable_navire', ['id_resp'], ['id_resp'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
